[workspace]
resolver = "3"
members = [
    "freeze-font",
    "freeze-font-cli"
]

[workspace.package]
authors = ["Stephane Raux <stephaneyfx@gmail.com>"]
edition = "2024"
license = "0BSD"
homepage = "https://github.com/stephaneyfx/freeze-font"
repository = "https://github.com/stephaneyfx/freeze-font.git"

[workspace.dependencies]
itertools = "0.15.0"
read-fonts = "0.44.0"
url = "2.5.8"
write-fonts = "0.53.0"
