[package]
name = "freeze-font"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description = "Tools to freeze opentype features"
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
either = "1.17.0"
enum-iterator = "2.3.0"
itertools = "0.15.0"
read-fonts = "0.42.1"
thiserror = "2.0.19"
url = "2.5.8"
write-fonts = "0.51.0"
